// collegeMajors.js
const collegeMajors = [
    "Accounting",
    "Agricultural Business",
    "Agronomy",
    "Animal Science",
    "Anthropology",
    "Architecture",
    "Art History",
    "Athletic Training",
    "Biochemistry",
    "Biology",
    "Biomedical Engineering",
    "Broadcast Journalism",
    "Business Administration",
    "Business Analytics",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Classical Studies",
    "Cognitive Science",
    "Communication Studies",
    "Computer Engineering",
    "Computer Science",
    "Criminal Justice",
    "Culinary Arts",
    "Dance",
    "Data Science",
    "Dietetics",
    "Digital Media",
    "Early Childhood Education",
    "Economics",
    "Education",
    "Electrical Engineering",
    "Elementary Education",
    "English Literature",
    "Entrepreneurship",
    "Environmental Engineering",
    "Environmental Policy",
    "Environmental Science",
    "Event Planning",
    "Exercise Science",
    "Film Studies",
    "Finance",
    "Fine Arts",
    "Forestry",
    "Geography",
    "Geology",
    "Global Studies",
    "Graphic Design",
    "Health Administration",
    "Health Sciences",
    "History",
    "Horticulture",
    "Hospitality Management",
    "Hotel Management",
    "Human Resource Management",
    "Industrial Engineering",
    "Interior Design",
    "International Business",
    "International Law",
    "International Relations",
    "Journalism",
    "Landscape Architecture",
    "Legal Studies",
    "Liberal Arts",
    "Linguistics",
    "Management",
    "Marketing",
    "Mathematics",
    "Mechanical Engineering",
    "Media Studies",
    "Music",
    "Nuclear Engineering",
    "Nursing",
    "Nutrition",
    "Occupational Therapy",
    "Pharmacy",
    "Philosophy",
    "Physical Education",
    "Physical Therapy",
    "Physics",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Public Health",
    "Public Policy",
    "Public Relations",
    "Radiologic Technology",
    "Real Estate",
    "Religious Studies",
    "Secondary Education",
    "Social Work",
    "Sociology",
    "Software Engineering",
    "Special Education",
    "Speech-Language Pathology",
    "Sports Communication",
    "Sports Management",
    "Statistics",
    "Studio Art",
    "Supply Chain Management",
    "Theatre",
    "Tourism Management",
    "Urban Planning",
    "Urban Studies",
    "Wildlife Management",
    "Women and Gender Studies"
  ];
  
  export default collegeMajors;
  